name: maana-ariadne
channels:
  - defaults
dependencies:
  - astroid=2.3.3=py37_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - isort=4.3.21=py37_0
  - lazy-object-proxy=1.4.3=py37h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - mccabe=0.6.1=py37_1
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_3
  - pip=19.3.1=py37_0
  - pylint=2.4.4=py37_0
  - python=3.7.5=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h1de35cc_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /opt/anaconda3/envs/maana-ariadne

